-- Portal Monitoring Agent — initial schema.
--
-- Written by hand, idempotent, same convention as the Vault project. This is
-- NOT generated by drizzle-kit: generated migrations drift from what is really
-- applied to Supabase, and they give you nowhere to put IF NOT EXISTS, which is
-- the thing that makes a re-run safe.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── Tenancy ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "clients" (
  "id"            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "slug"          text NOT NULL,
  "name"          text NOT NULL,
  "commune_insee" text[] NOT NULL DEFAULT '{}',
  "active"        boolean NOT NULL DEFAULT true,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"    timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "clients_slug_unique" ON "clients" ("slug");

CREATE TABLE IF NOT EXISTS "users" (
  "id"            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "email"         text NOT NULL,
  "name"          text,
  "password_hash" text,
  "role"          text NOT NULL DEFAULT 'member',
  "client_id"     uuid REFERENCES "clients"("id") ON DELETE SET NULL,
  "active"        boolean NOT NULL DEFAULT true,
  "last_login_at" timestamp with time zone,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"    timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_unique" ON "users" ("email");

-- ── Sources ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "portal_sources" (
  "id"              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "key"             text NOT NULL,
  "name"            text NOT NULL,
  "hosts"           text[] NOT NULL DEFAULT '{}',
  "discovery_mode"  text NOT NULL,
  "base_url"        text NOT NULL,
  "crawl_delay_ms"  integer NOT NULL DEFAULT 1000,
  "enabled"         boolean NOT NULL DEFAULT false,
  "permission_note" text,
  "config"          jsonb NOT NULL DEFAULT '{}'::jsonb,
  "last_run_at"     timestamp with time zone,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"      timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "portal_sources_key_unique" ON "portal_sources" ("key");

CREATE TABLE IF NOT EXISTS "client_sources" (
  "id"         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "client_id"  uuid NOT NULL REFERENCES "clients"("id") ON DELETE CASCADE,
  "source_id"  uuid NOT NULL REFERENCES "portal_sources"("id") ON DELETE CASCADE,
  "enabled"    boolean NOT NULL DEFAULT true,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "client_sources_pair_unique"
  ON "client_sources" ("client_id", "source_id");

-- ── Collection ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "portal_runs" (
  "id"             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "source_id"      uuid NOT NULL REFERENCES "portal_sources"("id") ON DELETE CASCADE,
  "mode"           text NOT NULL DEFAULT 'scheduled',
  "status"         text NOT NULL DEFAULT 'running',
  "commune_insee"  text[] NOT NULL DEFAULT '{}',
  "seen_count"     integer NOT NULL DEFAULT 0,
  "new_count"      integer NOT NULL DEFAULT 0,
  "gone_count"     integer NOT NULL DEFAULT 0,
  "fetched_count"  integer NOT NULL DEFAULT 0,
  "parsed_count"   integer NOT NULL DEFAULT 0,
  "failed_count"   integer NOT NULL DEFAULT 0,
  "aborted_reason" text,
  "error"          text,
  "started_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "completed_at"   timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "portal_runs_source_started_idx"
  ON "portal_runs" ("source_id", "started_at" DESC);

CREATE TABLE IF NOT EXISTS "portal_snapshots" (
  "id"           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "source_id"    uuid NOT NULL REFERENCES "portal_sources"("id") ON DELETE CASCADE,
  "run_id"       uuid REFERENCES "portal_runs"("id") ON DELETE SET NULL,
  "external_id"  text NOT NULL,
  "url"          text NOT NULL,
  "s3_key"       text NOT NULL,
  "byte_size"    integer,
  "content_hash" text NOT NULL,
  "fetched_at"   timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "portal_snapshots_lookup_idx"
  ON "portal_snapshots" ("source_id", "external_id", "fetched_at" DESC);

-- ── Agencies ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "portal_agencies" (
  "id"              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name"            text NOT NULL,
  "name_normalized" text NOT NULL,
  "address"         text,
  "postal_code"     text,
  "city"            text,
  "phone"           text,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"      timestamp with time zone NOT NULL DEFAULT now()
);
-- NULLS NOT DISTINCT so two rows with the same name and no postcode collide
-- rather than silently multiplying. Without it, an agency whose address we
-- never captured gets a new row on every run.
CREATE UNIQUE INDEX IF NOT EXISTS "portal_agencies_identity_unique"
  ON "portal_agencies" ("name_normalized", "postal_code") NULLS NOT DISTINCT;

-- ── Properties ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "properties" (
  "id"              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "title"           text,
  "description"     text,
  "price_eur"       bigint,
  "area_m2"         numeric,
  "land_m2"         numeric,
  "rooms"           integer,
  "bedrooms"        integer,
  "property_type"   text,
  "commune_insee"   text,
  "agency_id"       uuid REFERENCES "portal_agencies"("id") ON DELETE SET NULL,
  "agency_ref"      text,
  "source_count"    integer NOT NULL DEFAULT 1,
  "status"          text NOT NULL DEFAULT 'active',
  "first_listed_at" timestamp with time zone,
  "last_seen_at"    timestamp with time zone,
  "delisted_at"     timestamp with time zone,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"      timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "properties_commune_idx" ON "properties" ("commune_insee");
CREATE INDEX IF NOT EXISTS "properties_agency_ref_idx" ON "properties" ("agency_id", "agency_ref");

-- ── Listings ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "portal_listings" (
  "id"                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "source_id"         uuid NOT NULL REFERENCES "portal_sources"("id") ON DELETE CASCADE,
  "external_id"       text NOT NULL,
  "url"               text NOT NULL,
  "property_id"       uuid REFERENCES "properties"("id") ON DELETE SET NULL,
  "match_confidence"  numeric,
  "match_signals"     jsonb,
  "status"            text NOT NULL DEFAULT 'active',
  "title"             text,
  "description"       text,
  "price_eur"         bigint,
  "price_per_m2"      integer,
  "area_m2"           numeric,
  "land_m2"           numeric,
  "rooms"             integer,
  "bedrooms"          integer,
  "bathrooms"         integer,
  "property_type"     text,
  "commune_insee"     text,
  "commune_raw"       text,
  "postal_code"       text,
  "lat"               numeric,
  "lon"               numeric,
  "agency_id"         uuid REFERENCES "portal_agencies"("id") ON DELETE SET NULL,
  "agency_ref"        text,
  "availability"      text,
  "published_at"      timestamp with time zone,
  "source_updated_at" timestamp with time zone,
  "first_seen_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "last_seen_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "delisted_at"       timestamp with time zone,
  "parse_status"      text NOT NULL DEFAULT 'ok',
  "parse_error"       text,
  "raw"               jsonb,
  "created_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"        timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "portal_listings_source_external_unique"
  ON "portal_listings" ("source_id", "external_id");
CREATE INDEX IF NOT EXISTS "portal_listings_property_idx" ON "portal_listings" ("property_id");
CREATE INDEX IF NOT EXISTS "portal_listings_commune_status_idx"
  ON "portal_listings" ("commune_insee", "status");
CREATE INDEX IF NOT EXISTS "portal_listings_agency_ref_idx"
  ON "portal_listings" ("agency_id", "agency_ref");

-- ── Events ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "portal_listing_events" (
  "id"          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "listing_id"  uuid NOT NULL REFERENCES "portal_listings"("id") ON DELETE CASCADE,
  "property_id" uuid REFERENCES "properties"("id") ON DELETE SET NULL,
  "source_id"   uuid NOT NULL REFERENCES "portal_sources"("id") ON DELETE CASCADE,
  "run_id"      uuid REFERENCES "portal_runs"("id") ON DELETE SET NULL,
  "type"        text NOT NULL,
  "price_from"  bigint,
  "price_to"    bigint,
  "payload"     jsonb,
  "occurred_at" timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "portal_listing_events_listing_idx"
  ON "portal_listing_events" ("listing_id", "occurred_at" DESC);
CREATE INDEX IF NOT EXISTS "portal_listing_events_property_idx"
  ON "portal_listing_events" ("property_id", "occurred_at" DESC);
CREATE INDEX IF NOT EXISTS "portal_listing_events_type_idx"
  ON "portal_listing_events" ("type", "occurred_at" DESC);

-- ── Settings ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "settings" (
  "key"        text PRIMARY KEY,
  "value"      text,
  "encrypted"  boolean NOT NULL DEFAULT false,
  "updated_by" uuid REFERENCES "users"("id") ON DELETE SET NULL,
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
